# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: true
  path: source
- script: |
    SET DEVENV_HOME=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
    echo %DEVENV_HOME%
    dir
    "%DEVENV_HOME%"devenv.exe AdventureWorksExample.dtproj /out builderrors.txt
    type builderrors.txt
  workingDirectory: $(Agent.BuildDirectory)\source\SLN_AdventureWorksExample\AdventureWorksExample
  displayName: Build SSIS Project
- publish: $(Agent.BuildDirectory)\source\SLN_AdventureWorksExample\AdventureWorksExample\bin\Development
  artifact: AdventureWorksExample.ispac
